### ISSUE TITLE
rustls-acceptor

### ISSUE THREAD

**Issue by bradyjoestar** [Keruspe/rustls-connector#1]
Do you have a plan for supporing `rustls-acceptor` ?

I really love this project! :smile:
Maybe we could move it to `rust-native-tls` https://github.com/sfackler/rust-native-tls

So the crate which depend on rust-native-tls will benefit the performance of rustls.

**Comment by Keruspe** [comment]
Hi,

Yes I plan on supporting rustls-connector.

I don't see how it would make sense to move it to native-tls
